return {
    turret_shoot             = 'assets/sounds/turrets/sci-fi_weapon_rifle_bolt_shot_01.wav',
    turret_powered           = 'assets/sounds/generator/sci-fi_power_on_rise_beep_01.wav',
    enemy_death1             = 'assets/sounds/enemies/bone_break_neck_snap_crack_01.wav',
    enemy_death2             = 'assets/sounds/enemies/bone_break_neck_snap_crack_02.wav',
    enemy_death3             = 'assets/sounds/enemies/bone_break_neck_snap_crack_03.wav',
    enemy_death4             = 'assets/sounds/enemies/bone_break_neck_snap_crack_04.wav',
    enemy_death_impact       = 'assets/sounds/enemies/punch_grit_wet_impact_03.wav',
    background_engine_hum    = 'assets/sounds/ship/sci-fi_spaceship_background_room_tone_hum_loop_01.wav',
    powergrid_activate       = 'assets/sounds/generator/sci-fi_power_up_object_01.wav',
    powergrid_activate_layer = 'assets/sounds/generator/sci-fi_spark_electric_device_active_03.wav',
    powergrid_zap1           = 'assets/sounds/generator/zap1.wav',
    powergrid_zap2           = 'assets/sounds/generator/zap2.wav',
    powergrid_zap3           = 'assets/sounds/generator/zap3.wav',
    powergrid_zap4           = 'assets/sounds/generator/zap4.wav',
    powergrid_powered        = 'assets/sounds/generator/sci-fi_power_on_rise_beep_01.wav',
    dynamo_open              = 'assets/sounds/widgets/switch_button_push_on_off_01.wav',
    dynamo_close             = 'assets/sounds/widgets/switch_button_push_on_off_02.wav',
    widget_button_press      = 'assets/sounds/widgets/button/switch_button_push_on_off_08.wav',
    widget_wheel             = 'assets/sounds/widgets/wheel/lever_turn_push_crank_handle_small_13.wav',
    widget_wheel_turn        = 'assets/sounds/widgets/wheel/metal_rattle_spin_small_02.wav',
    widget_wheel_tick        = 'assets/sounds/widgets/wheel/metal_small_impact_01.wav',
    widget_flick_spring      = 'assets/sounds/widgets/flick/spring.ogg',
    widget_flick_spring_pop  = 'assets/sounds/widgets/flick/spring_pop.ogg',
    low_power_siren          = 'assets/sounds/ship/alarm_siren_loop_11.wav',
}
